/**
 * Generator for a Cloudflare Workers MCP server project.
 *
 * Emits a complete, deployable Worker that serves the generated MCP server over
 * Streamable HTTP at /mcp using the Cloudflare Agents SDK `createMcpHandler`.
 * Reuses tool extraction + the shared tool-definition-map serialization; the
 * request-execution path is reimplemented Workers-native (global fetch, no
 * node:https) and argument validation uses build-time-emitted zod (no runtime eval).
 */
import { OpenAPIV3 } from 'openapi-types';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { McpToolDefinition } from '../types/index.js';
import { generateToolDefinitionMap } from '../utils/code-gen.js';

/** A single generated file, relative to the output project root. */
export interface GeneratedFile {
  path: string;
  content: string;
}

/** Inputs needed to generate the full Worker project. */
export interface CloudflareWorkerGenInput {
  tools: McpToolDefinition[];
  serverName: string;
  serverVersion: string;
  securitySchemes: OpenAPIV3.ComponentsObject['securitySchemes'];
  baseUrl: string;
}

/**
 * Generate every file for the Worker project. Returned paths are relative to the
 * output directory (e.g. "src/index.ts").
 */
export function generateCloudflareWorkerFiles(input: CloudflareWorkerGenInput): GeneratedFile[] {
  return [
    { path: 'src/index.ts', content: generateWorkerIndex(input) },
    { path: 'src/tools.ts', content: generateWorkerToolsFile(input) },
    { path: 'wrangler.jsonc', content: generateWranglerConfig(input) },
    { path: '.dev.vars.example', content: generateDevVarsExample(input) },
    { path: 'package.json', content: generateWorkerPackageJson(input) },
    { path: 'tsconfig.json', content: generateWorkerTsconfig() },
    { path: 'README.md', content: generateWorkerReadme(input) },
  ];
}

/**
 * Build a zod *shape source string* (the object passed as the 3rd arg to
 * server.tool) from a tool's JSON Schema. We emit `{ propName: z.<...>, ... }`.
 * Each property's zod is produced at generate time via json-schema-to-zod, so the
 * Worker ships real zod with no runtime eval.
 */
function generateZodShapeSource(tool: McpToolDefinition): string {
  const schema = tool.inputSchema;
  if (typeof schema === 'boolean' || !schema || typeof schema !== 'object') return '{}';
  const properties = (schema as { properties?: Record<string, unknown> }).properties;
  const required = new Set(
    Array.isArray((schema as { required?: string[] }).required)
      ? (schema as { required?: string[] }).required!
      : []
  );
  if (!properties || Object.keys(properties).length === 0) return '{}';

  const entries = Object.entries(properties).map(([key, propSchema]) => {
    // json-schema-to-zod emits a full `z....` expression for the sub-schema.
    let zodExpr: string;
    try {
      zodExpr = jsonSchemaToZod(propSchema as object);
    } catch {
      zodExpr = 'z.any()';
    }
    if (!required.has(key)) zodExpr = `${zodExpr}.optional()`;
    return `    ${JSON.stringify(key)}: ${zodExpr}`;
  });

  return `{\n${entries.join(',\n')}\n  }`;
}

export function generateWorkerToolsFile(input: CloudflareWorkerGenInput): string {
  const mapEntries = generateToolDefinitionMap(input.tools, input.securitySchemes);
  const shapeEntries = input.tools
    // Cast each shape literal to ZodRawShape: an object literal containing
    // ZodOptional<...> members is inferred too narrowly and fails the map value's
    // index signature under strict mode without the widening cast.
    .map((t) => `  [${JSON.stringify(t.name)}, ${generateZodShapeSource(t)} as z.ZodRawShape],`)
    .join('\n');

  return `/**
 * Tool definitions + zod input shapes for the generated MCP Worker.
 * Generated by openapi-mcp-generator. Do not edit by hand.
 */
import { z } from 'zod';

export interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: any;
  method: string;
  pathTemplate: string;
  executionParameters: { name: string; in: string }[];
  requestBodyContentType?: string;
  securityRequirements: any[];
  tags: string[];
  deprecated: boolean;
}

export const toolDefinitionMap: Map<string, McpToolDefinition> = new Map([
${mapEntries}
]);

/**
 * Build-time zod input shapes, keyed by tool name (consumed by server.tool).
 * Typed as ZodRawShape so optional members (ZodOptional<...>) are accepted under
 * strict mode — a plain Record<string, ZodTypeAny> rejects \`undefined\`-bearing
 * optional values at the index signature.
 */
export const toolZodShapes: Map<string, z.ZodRawShape> = new Map([
${shapeEntries}
]);
`;
}

/** Runtime-relevant subset of a security scheme, embedded into the generated index.ts. */
interface RuntimeSecurityScheme {
  type: string;
  in?: string;
  name?: string;
  scheme?: string;
  tokenUrl?: string | null;
}

/**
 * Build a name -> runtime-metadata map from the spec's security schemes, capturing only
 * what the generated `applyAuth` needs at runtime. The spec is dereferenced upstream, so
 * `$ref` entries are skipped (guarded by a `'type' in scheme` check).
 */
function buildRuntimeSecuritySchemes(
  securitySchemes: OpenAPIV3.ComponentsObject['securitySchemes']
): Record<string, RuntimeSecurityScheme> {
  const map: Record<string, RuntimeSecurityScheme> = {};
  const schemes = securitySchemes ?? {};
  for (const [name, raw] of Object.entries(schemes)) {
    if (!raw || typeof raw !== 'object' || !('type' in raw)) continue;
    const scheme = raw as OpenAPIV3.SecuritySchemeObject;
    if (scheme.type === 'apiKey') {
      map[name] = { type: 'apiKey', in: scheme.in, name: scheme.name };
    } else if (scheme.type === 'http') {
      map[name] = { type: 'http', scheme: scheme.scheme };
    } else if (scheme.type === 'oauth2') {
      const tokenUrl = scheme.flows?.clientCredentials?.tokenUrl ?? null;
      map[name] = { type: 'oauth2', tokenUrl };
    } else {
      // openIdConnect or any other type: record the type so runtime can ignore gracefully.
      map[name] = { type: scheme.type };
    }
  }
  return map;
}

export function generateWorkerIndex(input: CloudflareWorkerGenInput): string {
  const securitySchemesJson = JSON.stringify(
    buildRuntimeSecuritySchemes(input.securitySchemes),
    null,
    2
  );
  return `/**
 * Cloudflare Worker MCP server (Streamable HTTP at /mcp).
 * Generated by openapi-mcp-generator. Deploy with: npx wrangler deploy
 */
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js';
import { toolDefinitionMap, toolZodShapes, type McpToolDefinition } from './tools.js';

const SERVER_NAME = ${JSON.stringify(input.serverName)};
const SERVER_VERSION = ${JSON.stringify(input.serverVersion)};
const MCP_ROUTE = '/mcp';

export interface Env {
  /** Upstream API base URL (set in wrangler.jsonc vars or as a secret). */
  API_BASE_URL?: string;
  /** Secrets are injected at runtime via \`wrangler secret put\`. */
  [key: string]: string | undefined;
}

// A fresh McpServer is created per request. MCP SDK >= 1.26 throws if a server
// instance is connected to more than one transport, and sharing instances across
// requests can leak one client's responses to another — so this must NOT be hoisted
// to module scope.
function createServer(env: Env): McpServer {
  const server = new McpServer({ name: SERVER_NAME, version: SERVER_VERSION });
  for (const [name, def] of toolDefinitionMap) {
    const shape = toolZodShapes.get(name) ?? {};
    server.tool(name, def.description, shape, (args: Record<string, unknown>) =>
      executeApiTool(def, args, env)
    );
  }
  return server;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname !== MCP_ROUTE) {
      return new Response('Not found', { status: 404 });
    }
    // New server + transport per request (stateless, SDK >= 1.26 safe).
    const server = createServer(env);
    const transport = new WebStandardStreamableHTTPServerTransport();
    await server.connect(transport);
    return transport.handleRequest(request);
  },
} satisfies ExportedHandler<Env>;

const DEFAULT_BASE_URL = ${JSON.stringify(input.baseUrl)};

/** Runtime metadata for the spec's security schemes (embedded at generate time). */
const SECURITY_SCHEMES: Record<string, { type: string; in?: string; name?: string; scheme?: string; tokenUrl?: string | null }> = ${securitySchemesJson};

/** Execute one tool by issuing the upstream HTTP request via global fetch. */
async function executeApiTool(
  def: McpToolDefinition,
  args: Record<string, unknown>,
  env: Env
): Promise<{ content: { type: 'text'; text: string }[]; isError?: boolean }> {
  try {
    const baseUrl = (env.API_BASE_URL || DEFAULT_BASE_URL || '').replace(/\\/+$/, '');
    // Substitute path params.
    let pathName = def.pathTemplate;
    const queryParams = new URLSearchParams();
    let bodyArg: unknown;

    for (const p of def.executionParameters) {
      const value = args[p.name];
      if (value === undefined || value === null) continue;
      if (p.in === 'path') {
        pathName = pathName.replace(
          new RegExp('\\\\{' + p.name + '\\\\}', 'g'),
          encodeURIComponent(String(value))
        );
      } else if (p.in === 'query') {
        if (Array.isArray(value)) queryParams.set(p.name, value.map(String).join(','));
        else queryParams.set(p.name, String(value));
      } else if (p.in === 'header') {
        // collected below into headers
      }
    }
    if ('requestBody' in args) bodyArg = (args as { requestBody?: unknown }).requestBody;

    const url = new URL(baseUrl + pathName);
    queryParams.forEach((v, k) => url.searchParams.set(k, v));

    const headers: Record<string, string> = { accept: 'application/json' };
    for (const p of def.executionParameters) {
      if (p.in === 'header' && args[p.name] != null) headers[p.name] = String(args[p.name]);
    }

    let body: string | undefined;
    if (bodyArg !== undefined && def.requestBodyContentType) {
      headers['content-type'] = def.requestBodyContentType;
      body =
        def.requestBodyContentType.includes('json') ? JSON.stringify(bodyArg) : String(bodyArg);
    }

    await applyAuth(def, env, headers, url);

    const response = await fetch(url.toString(), { method: def.method.toUpperCase(), headers, body });
    const contentType = response.headers.get('content-type') ?? '';
    const text = await response.text();

    if (!response.ok) {
      return {
        isError: true,
        content: [{ type: 'text', text: \`Upstream API error \${response.status}: \${text}\` }],
      };
    }
    const pretty = contentType.includes('json')
      ? safePrettyJson(text)
      : text;
    return { content: [{ type: 'text', text: pretty }] };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { isError: true, content: [{ type: 'text', text: \`Tool execution failed: \${message}\` }] };
  }
}

function safePrettyJson(text: string): string {
  try {
    return JSON.stringify(JSON.parse(text), null, 2);
  } catch {
    return text;
  }
}

/**
 * Inject auth from env per the tool's security requirements, branching on each scheme's
 * actual type/placement (from SECURITY_SCHEMES). The first satisfiable scheme wins.
 * Async because oauth2 client-credentials performs a token fetch.
 */
async function applyAuth(
  def: McpToolDefinition,
  env: Env,
  headers: Record<string, string>,
  url: URL
): Promise<void> {
  // securityRequirements is an array of { schemeName: scopes[] } objects.
  for (const requirement of def.securityRequirements) {
    for (const schemeName of Object.keys(requirement)) {
      const upper = schemeName.toUpperCase().replace(/[^A-Z0-9]/g, '_');
      const scheme = SECURITY_SCHEMES[schemeName];
      if (!scheme) continue;

      if (scheme.type === 'apiKey') {
        const key = env[\`\${upper}_API_KEY\`] ?? env.API_KEY;
        if (!key) continue;
        const paramName = scheme.name ?? 'apiKey';
        if (scheme.in === 'query') {
          url.searchParams.set(paramName, key);
        } else if (scheme.in === 'cookie') {
          const existing = headers['cookie'];
          const cookiePair = paramName + '=' + encodeURIComponent(key);
          headers['cookie'] = (existing ? existing + '; ' : '') + cookiePair;
        } else {
          // 'header' or unknown placement.
          headers[paramName.toLowerCase()] = key;
        }
        return;
      }

      if (scheme.type === 'http' && scheme.scheme === 'basic') {
        const user = env[\`\${upper}_USERNAME\`] ?? env.API_USERNAME;
        if (!user) continue;
        const pass = env[\`\${upper}_PASSWORD\`] ?? env.API_PASSWORD ?? '';
        headers['authorization'] = 'Basic ' + btoa(\`\${user}:\${pass}\`);
        return;
      }

      if (scheme.type === 'http') {
        // bearer or any other http scheme: generic token.
        const token = env[\`\${upper}_TOKEN\`] ?? env.API_TOKEN;
        if (!token) continue;
        headers['authorization'] = \`Bearer \${token}\`;
        return;
      }

      if (scheme.type === 'oauth2') {
        const clientId = env[\`\${upper}_CLIENT_ID\`] ?? env.OAUTH_CLIENT_ID;
        const clientSecret = env[\`\${upper}_CLIENT_SECRET\`] ?? env.OAUTH_CLIENT_SECRET;
        const tokenUrl = scheme.tokenUrl ?? env[\`\${upper}_TOKEN_URL\`] ?? env.OAUTH_TOKEN_URL;
        if (!clientId || !clientSecret || !tokenUrl) continue;
        try {
          // Forward the operation's required scopes (from securityRequirements)
          // so scope-gated token servers (Auth0/Okta/Azure AD) issue a usable token.
          const tokenBody = new URLSearchParams({ grant_type: 'client_credentials' });
          const scopes = requirement[schemeName];
          if (Array.isArray(scopes) && scopes.length > 0) {
            tokenBody.set('scope', scopes.join(' '));
          }
          const tokenResponse = await fetch(tokenUrl, {
            method: 'POST',
            headers: {
              accept: 'application/json',
              'content-type': 'application/x-www-form-urlencoded',
              authorization: 'Basic ' + btoa(\`\${clientId}:\${clientSecret}\`),
            },
            body: tokenBody.toString(),
          });
          if (!tokenResponse.ok) continue;
          const tokenData = (await tokenResponse.json()) as { access_token?: string };
          const accessToken = tokenData.access_token;
          if (!accessToken) continue;
          headers['authorization'] = \`Bearer \${accessToken}\`;
          return;
        } catch {
          // On token-fetch failure, leave auth unset; the upstream call surfaces a 401.
          continue;
        }
      }
    }
  }
}
`;
}

export function generateWranglerConfig(input: CloudflareWorkerGenInput): string {
  // compatibility_date pinned to a known-good date; nodejs_compat enables Node built-ins
  // some MCP/zod code paths expect. vars holds non-secret config only.
  return `{
  // Cloudflare Worker config. Docs: https://developers.cloudflare.com/workers/wrangler/configuration/
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": ${JSON.stringify(input.serverName)},
  "main": "src/index.ts",
  "compatibility_date": "2025-06-01",
  "compatibility_flags": ["nodejs_compat"],
  "observability": { "enabled": true },
  // Non-secret config. Secrets (API keys, tokens, passwords) must be set with
  // \`wrangler secret put <NAME>\` and are never stored here.
  "vars": {
    "API_BASE_URL": ${JSON.stringify(input.baseUrl)}
  }
}
`;
}

export function generateDevVarsExample(input: CloudflareWorkerGenInput): string {
  const lines = [
    '# Local development secrets for `wrangler dev`. Copy to `.dev.vars`.',
    '#',
    '# In production set these with: wrangler secret put <NAME>',
    '',
  ];
  const schemes = input.securitySchemes ?? {};
  const names = Object.keys(schemes);
  if (names.length === 0) {
    lines.push(
      '# This API declares no security schemes. Add secrets here if your API needs them, e.g.:'
    );
    lines.push('# API_KEY="your-key"');
  } else {
    for (const name of names) {
      const upper = name.toUpperCase().replace(/[^A-Z0-9]/g, '_');
      const scheme = schemes[name] as OpenAPIV3.SecuritySchemeObject;
      if (scheme && 'type' in scheme && scheme.type === 'http' && scheme.scheme === 'basic') {
        lines.push(`${upper}_USERNAME="..."`, `${upper}_PASSWORD="..."`);
      } else if (scheme && 'type' in scheme && scheme.type === 'http') {
        lines.push(`${upper}_TOKEN="..."`);
      } else if (scheme && 'type' in scheme && scheme.type === 'oauth2') {
        lines.push(`${upper}_CLIENT_ID="..."`, `${upper}_CLIENT_SECRET="..."`);
        const tokenUrl = scheme.flows?.clientCredentials?.tokenUrl;
        if (!tokenUrl) {
          lines.push(`${upper}_TOKEN_URL="..."`);
        }
      } else {
        lines.push(`${upper}_API_KEY="..."`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

export function generateWorkerPackageJson(input: CloudflareWorkerGenInput): string {
  const data = {
    name: input.serverName,
    version: input.serverVersion,
    description: `Cloudflare Worker MCP server generated from OpenAPI spec for ${input.serverName}`,
    private: true,
    type: 'module',
    scripts: {
      dev: 'wrangler dev',
      deploy: 'wrangler deploy',
      'cf-typegen': 'wrangler types',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      // Raw Streamable HTTP transport (WebStandardStreamableHTTPServerTransport)
      // ships in @modelcontextprotocol/sdk >= 1.26; no Cloudflare `agents` package
      // is needed for a stateless MCP Worker.
      '@modelcontextprotocol/sdk': '^1.26.0',
      zod: '^3.24.3',
    },
    devDependencies: {
      '@cloudflare/workers-types': '^4.20250601.0',
      typescript: '^5.8.3',
      wrangler: '^4.0.0',
    },
  };
  return JSON.stringify(data, null, 2) + '\n';
}

export function generateWorkerTsconfig(): string {
  const data = {
    compilerOptions: {
      target: 'es2022',
      module: 'esnext',
      moduleResolution: 'bundler',
      lib: ['es2022'],
      types: ['@cloudflare/workers-types'],
      strict: true,
      skipLibCheck: true,
      esModuleInterop: true,
      resolveJsonModule: true,
      noEmit: true,
    },
    include: ['src/**/*.ts'],
  };
  return JSON.stringify(data, null, 2) + '\n';
}

export function generateWorkerReadme(input: CloudflareWorkerGenInput): string {
  const schemeMap = input.securitySchemes ?? {};
  const schemes = Object.keys(schemeMap);
  const secretLines =
    schemes.length === 0
      ? '   (This API declares no security schemes — add any secrets your API needs.)'
      : schemes
          .map((n) => {
            const upper = n.toUpperCase().replace(/[^A-Z0-9]/g, '_');
            const scheme = schemeMap[n] as OpenAPIV3.SecuritySchemeObject;
            // Emit the secret name(s) that match this scheme's type so the deploy
            // hint stays in sync with .dev.vars.example.
            if (scheme && 'type' in scheme && scheme.type === 'oauth2') {
              const hasTokenUrl = Boolean(
                (scheme as OpenAPIV3.OAuth2SecurityScheme).flows?.clientCredentials?.tokenUrl
              );
              const oauthLines = [
                `   npx wrangler secret put ${upper}_CLIENT_ID`,
                `   npx wrangler secret put ${upper}_CLIENT_SECRET`,
              ];
              // When the spec omits the token URL, it must be supplied as a secret too.
              if (!hasTokenUrl) {
                oauthLines.push(`   npx wrangler secret put ${upper}_TOKEN_URL`);
              }
              return oauthLines.join('\n');
            }
            if (scheme && 'type' in scheme && scheme.type === 'http' && scheme.scheme === 'basic') {
              return `   npx wrangler secret put ${upper}_USERNAME\n   npx wrangler secret put ${upper}_PASSWORD`;
            }
            if (scheme && 'type' in scheme && scheme.type === 'http') {
              return `   npx wrangler secret put ${upper}_TOKEN`;
            }
            return `   npx wrangler secret put ${upper}_API_KEY`;
          })
          .join('\n');
  return `# ${input.serverName}

A remote MCP server for **${input.serverName}**, generated by [openapi-mcp-generator](https://github.com/harsha-iiiv/openapi-mcp-generator) and ready to deploy on Cloudflare Workers.

It serves the Model Context Protocol over **Streamable HTTP** at \`/mcp\`.

## Deploy

1. Install dependencies:

   \`\`\`bash
   npm install
   \`\`\`

2. Set your upstream API secrets (encrypted, per-Worker):

\`\`\`bash
${secretLines}
\`\`\`

3. Deploy to your own Cloudflare account (Wrangler will prompt you to log in):

   \`\`\`bash
   npx wrangler deploy
   \`\`\`

   Your server will be live at \`https://${input.serverName}.<your-subdomain>.workers.dev/mcp\`.

## Local development

\`\`\`bash
cp .dev.vars.example .dev.vars   # fill in your secrets
npm run dev                      # http://localhost:8787/mcp
\`\`\`

## Configuration

- Non-secret config (e.g. \`API_BASE_URL\`) lives in \`wrangler.jsonc\` under \`vars\`.
- Secrets (API keys, tokens, passwords) are set with \`wrangler secret put\` and never committed.

## Connect a client

Use the [MCP Inspector](https://github.com/modelcontextprotocol/inspector) or, from Claude Desktop, the [mcp-remote](https://www.npmjs.com/package/mcp-remote) proxy pointed at your \`/mcp\` URL.
`;
}
